services:
  uav_sim_pychrono:
    image: ghcr.io/lucamarchiano/uav_sim_pychrono:1.0
    container_name: uav_sim_pychrono
    hostname: uav_sim_pychrono
    tty: true
    stdin_open: true
    environment:
      # Forward X11 display to container
      - DISPLAY=${DISPLAY}
      # Forward host user id and group id to manage folder ownership
      - UID=${UID}
      - GID=${GID}
    user: "${UID}:${GID}"
    volumes:
      # Mount X11 socket for GUI applications
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      # Mount DockerSharedFolder folder (/host/path:/container/path)
      - type: bind
        source: $HOME/DockerSharedFolder
        target: /home/user/DockerSharedFolder
