services:
  flightstack:
    image: ghcr.io/lucamarchiano/flightstack:2.0
    entrypoint: /entrypoint.sh
    command: bash
    working_dir: /home/user/FlightstackSharedFolder
    container_name: flightstack
    hostname: flightstack
    tty: true
    stdin_open: true
    environment:
      # Add timezone environment variable
      - TZ=America/New_York
      # Add ROS environmental variables
      - ROS_DOMAIN_ID=42
    volumes:
      # Mount entrypoint script
      - type: bind
        source: ./entrypoint.sh     
        target: /entrypoint.sh      

networks:
  default:
    name: rosnet