services:
  pychrono:
    environment:
      # Forward X11 display to container
      - DISPLAY=host.docker.internal:0
    volumes: 
      # # Mount X11 socket for GUI applications
      # - type: bind
      #   source: /tmp/.X11-unix
      #   target: /tmp/.X11-unix
      # Mount PyChronoSharedFolder folder (/host/path:/container/path)
      - type: bind
        source: $HOST_SHARED_DIR
        target: /home/user/PyChronoSharedFolder
