services:
  pychrono:
    environment:
      # Forward display to container
      - DISPLAY=host.docker.internal:0
    volumes: 
      # Mount PyChronoSharedFolder folder 
      - type: bind
        source: $HOST_SHARED_DIR
        target: /home/user/PyChronoSharedFolder
